# https://gohugo.io/getting-started/configuration/
# https://pygments.org/styles/
# https://github.com/rhazdon/hugo-theme-hello-friend-ng

baseURL: "localhost"
languageCode: en-us
title: Daniel Cruz-Castro
theme: hello-friend-ng
enableRobotsTXT: true # Am I missing this file?
disable404: false
enableEmoji: true
PygmentsCodeFences: true
PygmentsStyle: "monokai" 
buildDrafts: false
enableGitInfo: true
copyright: "License"

params:
  author:
    name: "Daniel Cruz-Castro"
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"
  homeSubtitle: "I dont know what I'm doing but dang is it fun"
  description: "Daniels personal site"
  enableThemeToggle: true
  portrait:
    path: "images/square_me.jpg"
    alt: "This is me"
    maxWidth: "150px"
  logo:
    logoMark: ">"
    logoText: "$ cd /Users/daniels/dev/"
    logoHomeLink: "/"
  social:
    - name: "github"
      url: "https://github.com/DanDigits"
    - name: "linkedin"
      url: "LINKEDIN_LINK"
  footer:
    trademark: 2024
    rss: false
    copyright: false
    author: false
    # bottomText:
    topText:
      - "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
      - "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"

  # plausibleDataDomain: 'https://daniels.dev'
  # plausibleScriptSource: 'https://plausible.io/js/script.js'
  # csp: UNCOMMENT ONCE PLAUSIBLE PARTIAL IN PLACE
  #   scriptsrc:
  #   - "'self'"
  #   - "'https://plausible.io'"
  #   connectsrc:
  #   - "'self'"
  #   - "'unsafe-inline'"
  #   - "'https://plausible.io'"

  matchers:
    # cached with gzip compression enabled
    - pattern: "^.+\\.(js|css|md|otf|svg|ttf|txt)$"
      cacheControl: "max-age=604800, no-transform, public"
      gzip: true
    # cached with gzip compression disabled
    - pattern: "^.+\\.(bmp|gif|ico|jpeg|jpg|mp3|mp4|pdf|png|rss|tiff|woff|woff2)$"
      cacheControl: "max-age=604800, no-transform, public"
      gzip: false
    # sitemap gets a special content-type header
    - pattern: "^sitemap\\.xml$"
      contentType: "application/xml"
      cacheControl: "max-age=3600, no-transform, public"
      gzip: true
    # cached with gzip compression enabled
    - pattern: "^.+\\.(html|json|xml)$"
      cacheControl: "max-age=3600, no-transform, public"
      gzip: true

deployment:
  targets:
    - name: daniels-dev
      URL: "s3://daniels-dev?region=us-east-1"
      cloudFrontDistributionID: CLOUDFRONT_ID

menu:
  main:
    - indentifier: Blog
      name: Blog
      url: /posts
      weight: 1
    # - indentifier: categories
    #   name: Categories
    #   url: /categories
    #   weight: 10
    # - indentifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 20
    - indentifier: About
      name: About
      url: /about
      weight: 100